# Generated by Django 4.0.3 on 2022-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_remove_historia_diagnostico_historia_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_historia',
            field=models.ManyToManyField(to='Pacientes.historia'),
        ),
    ]
